name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install coverage and Coveralls
      run: |
        pip install coverage coveralls

    - name: Run tests with coverage
      run: |
        coverage run -m pytest

    - name: Upload coverage to Coveralls
      run: |
        coveralls
